# Generated by Django 5.2.17 on 2026-09-08 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_status', models.CharField(choices=[('RETAIL', 'Cliente detal'), ('WHOLESALE_MAINTENANCE', 'Mayorista - mantenimiento'), ('WHOLESALE_ACTIVE', 'Mayorista activo'), ('WHOLESALE_GRACE', 'Mayorista - período de gracia'), ('WHOLESALE_EXPIRED', 'Mayorista vencido')], default='RETAIL', max_length=40, verbose_name='Estado comercial')),
                ('wholesale_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación mayorista')),
                ('maintenance_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite de mantenimiento')),
                ('grace_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del período de gracia')),
                ('grace_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite del período de gracia')),
                ('last_wholesale_purchase_at', models.DateTimeField(blank=True, null=True, verbose_name='Última compra mayorista válida')),
                ('last_wholesale_purchase_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de la última compra mayorista válida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil comercial',
                'verbose_name_plural': 'Perfiles comerciales',
                'ordering': ['user__first_name', 'user__last_name', 'user__email'],
            },
        ),
    ]
