# Generated by Django 5.2.17 on 2026-09-03 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencias'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada de inventario'), ('SALE', 'Venta'), ('RETURN', 'Devolución'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('previous_stock', models.PositiveIntegerField(default=0, editable=False, verbose_name='Existencias anteriores')),
                ('new_stock', models.PositiveIntegerField(default=0, editable=False, verbose_name='Existencias nuevas')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo / observación')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
