# Generated by Django 5.2.17 on 2026-09-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_stock_inventorymovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada de inventario'), ('RESERVATION', 'Reserva de pedido'), ('RESERVATION_RELEASE', 'Liberación de reserva'), ('SALE', 'Venta'), ('RETURN', 'Devolución'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo')], max_length=20, verbose_name='Tipo de movimiento'),
        ),
    ]
