# Generated by Django 5.2.17 on 2026-09-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_inventorymovement_movement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['menu_order', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='category',
            name='highlight_in_menu',
            field=models.BooleanField(default=False, verbose_name='Destacar en el menú'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='tag', max_length=60, verbose_name='Icono Lucide'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden en el menú'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Mostrar en menú principal'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='Slug'),
        ),
    ]
