# Generated by Django 5.2.17 on 2026-09-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options_category_highlight_in_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('sparkles', '✨ Brillos / maquillaje'), ('heart', '❤️ Corazón'), ('droplets', '💧 Gotas / cuidado personal'), ('shirt', '👕 Ropa / moda'), ('badge-percent', '🏷️ Promoción / descuento'), ('gem', '💎 Accesorios / joyería'), ('tag', '🔖 Etiqueta'), ('shopping-bag', '🛍️ Bolsa de compras'), ('gift', '🎁 Regalo'), ('star', '⭐ Estrella'), ('palette', '🎨 Belleza / colores'), ('crown', '👑 Premium'), ('baby', '👶 Infantil / bebé'), ('watch', '⌚ Relojes'), ('glasses', '👓 Gafas'), ('footprints', '👣 Calzado'), ('flower-2', '🌸 Floral / femenino'), ('smile', '😊 Kawaii / divertido'), ('package', '📦 Otros productos')], default='tag', max_length=60, verbose_name='Icono'),
        ),
    ]
