# Generated by Django 5.2.17 on 2026-09-04 19:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_stock_inventorymovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de pedido')),
                ('customer_name', models.CharField(max_length=180, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('department', models.CharField(max_length=120, verbose_name='Departamento')),
                ('city', models.CharField(max_length=120, verbose_name='Ciudad / municipio')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección de entrega')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Indicaciones de entrega')),
                ('carrier', models.CharField(max_length=60, verbose_name='Transportadora')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PROOF_RECEIVED', 'Comprobante recibido'), ('PAYMENT_CONFIRMED', 'Pago confirmado'), ('PREPARING', 'Preparando pedido'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CHANGE_REQUESTED', 'Cambio solicitado'), ('CANCELED', 'Cancelado'), ('RESERVATION_EXPIRED', 'Reserva vencida')], default='PENDING_PAYMENT', max_length=30, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='Nombre del producto')),
                ('sku', models.CharField(max_length=60, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del pedido',
                'verbose_name_plural': 'Productos del pedido',
                'ordering': ['id'],
            },
        ),
    ]
