# Generated by Django 5.2.17 on 2026-09-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NEQUI', 'Nequi'), ('BANCOLOMBIA_KEY', 'Llave Bancolombia')], max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de carga del comprobante'),
        ),
    ]
