# Generated by Django 5.2.17 on 2026-09-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_payment_method_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_proof_uploaded_at',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación del pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('WOMPI', 'Wompi')], default='', max_length=30, verbose_name='Pasarela de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Estado en la pasarela'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ID de transacción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PSE', 'PSE'), ('NEQUI', 'Nequi'), ('BANCOLOMBIA_BUTTON', 'Botón Bancolombia'), ('KEY', 'Llave / Bre-B')], max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PAYMENT_PROCESSING', 'Pago en proceso'), ('PAYMENT_CONFIRMED', 'Pago confirmado'), ('PAYMENT_DECLINED', 'Pago rechazado'), ('PREPARING', 'Preparando pedido'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CHANGE_REQUESTED', 'Cambio solicitado'), ('CANCELED', 'Cancelado'), ('RESERVATION_EXPIRED', 'Reserva vencida')], default='PENDING_PAYMENT', max_length=30, verbose_name='Estado'),
        ),
    ]
