# Generated by Django 5.2.17 on 2026-09-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de carga del comprobante'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('NEQUI', 'Nequi'), ('BRE_B', 'Llave Bre-B'), ('BANCOLOMBIA', 'Bancolombia')], max_length=30, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PROOF_RECEIVED', 'Comprobante recibido'), ('PAYMENT_PROCESSING', 'Pago en proceso'), ('PAYMENT_CONFIRMED', 'Pago confirmado'), ('PAYMENT_DECLINED', 'Pago rechazado'), ('PREPARING', 'Preparando pedido'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CHANGE_REQUESTED', 'Cambio solicitado'), ('CANCELED', 'Cancelado'), ('RESERVATION_EXPIRED', 'Reserva vencida')], default='PENDING_PAYMENT', max_length=30, verbose_name='Estado'),
        ),
    ]
