# Generated by Django 5.2.17 on 2026-09-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_payment_proof_order_payment_proof_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Transportadora de despacho'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_notes',
            field=models.TextField(blank=True, verbose_name='Observaciones de despacho'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Número de guía'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(max_length=60, verbose_name='Transportadora solicitada'),
        ),
    ]
