# Generated by Django 5.2.17 on 2026-09-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commercial_benefit_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento comercial'),
        ),
        migrations.AddField(
            model_name='order',
            name='commercial_benefit_result',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Resultado comercial'),
        ),
    ]
