# Generated by Django 5.2.17 on 2026-09-09 02:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_commercial_benefit_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retail_reference_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total de referencia a precio detal'),
        ),
        migrations.AddField(
            model_name='order',
            name='wholesale_activation_qualified',
            field=models.BooleanField(default=False, verbose_name='Calificó para activación mayorista'),
        ),
    ]
