# Generated by Django 5.2.17 on 2026-09-10 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_retail_reference_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_shipping',
            field=models.BooleanField(default=False, verbose_name='Envío gratis'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total de productos'),
        ),
    ]
