# Generated by Django 5.2.17 on 2026-09-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_reservation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_reservation_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'No aplica'), ('ACTIVE', 'Reserva activa'), ('FINALIZED', 'Reserva convertida en venta'), ('RELEASED', 'Reserva liberada')], default='NOT_APPLICABLE', max_length=30, verbose_name='Estado de la reserva de inventario'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conversión a venta'),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de liberación de reserva'),
        ),
    ]
