# Generated by Django 5.2.17 on 2026-09-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_inventory_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de devolución'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('NOT_RETURNED', 'Sin devolución'), ('PARTIAL', 'Devolución parcial'), ('FULL', 'Devolución total')], default='NOT_RETURNED', max_length=30, verbose_name='Estado de devolución'),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de pago'), ('PROOF_RECEIVED', 'Comprobante recibido'), ('PAYMENT_PROCESSING', 'Pago en proceso'), ('PAYMENT_CONFIRMED', 'Pago confirmado'), ('PAYMENT_DECLINED', 'Pago rechazado'), ('PREPARING', 'Preparando pedido'), ('SHIPPED', 'Enviado'), ('DELIVERED', 'Entregado'), ('CHANGE_REQUESTED', 'Cambio solicitado'), ('RETURNED', 'Devuelto'), ('CANCELED', 'Cancelado'), ('RESERVATION_EXPIRED', 'Reserva vencida')], default='PENDING_PAYMENT', max_length=30, verbose_name='Estado'),
        ),
    ]
