# Generated by Django 5.2.17 on 2026-09-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_return_reason_order_return_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad devuelta'),
        ),
    ]
