# Generated by Django 5.2.17 on 2026-09-23 13:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_orderitem_returned_quantity'),
        ('catalog', '0004_alter_inventorymovement_movement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('PARTIAL', 'Devolución parcial'), ('FULL', 'Devolución total')], max_length=20, verbose_name='Tipo de devolución')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Motivo de devolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de devolución')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_return_records', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_records', to='cart.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Registro de devolución',
                'verbose_name_plural': 'Registros de devoluciones',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='Nombre del producto')),
                ('sku', models.CharField(max_length=60, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad devuelta')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_record_items', to='cart.orderitem', verbose_name='Producto original del pedido')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_record_items', to='catalog.product', verbose_name='Producto')),
                ('return_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.returnrecord', verbose_name='Devolución')),
            ],
            options={
                'verbose_name': 'Producto de devolución',
                'verbose_name_plural': 'Productos de devolución',
                'ordering': ['id'],
            },
        ),
    ]
