# Generated by Django 5.2.17 on 2026-10-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_returnrecord_returnrecorditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrecord',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Historial de devolución', 'verbose_name_plural': 'Historial de devoluciones'},
        ),
        migrations.AlterModelOptions(
            name='returnrecorditem',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de producto devuelto', 'verbose_name_plural': 'Detalle de productos devueltos'},
        ),
    ]
